using System.Collections.Generic;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Xamlizer.Models;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Xamlizer;

/// <summary>
/// Generates C# source code from a <see cref="XamlParseResult"/> using the Roslyn SyntaxFactory API.
/// </summary>
internal static class CSharpCodeGenerator
{
    // All C# reserved keywords that cannot be used as plain identifiers.
    private static readonly HashSet<string> CSharpKeywords = new HashSet<string>(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
        "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw",
        "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using",
        "virtual", "void", "volatile", "while",
    };

    /// <summary>
    /// Generates a C# source file from the parsed XAML result.
    /// </summary>
    public static string Generate(XamlParseResult parseResult, string namespaceName)
    {
        // Group entries by type in first-appearance order, preserving document order within each type.
        var typeOrder = new List<string>();
        var typeGroups = new Dictionary<string, List<XamlEntry>>(StringComparer.Ordinal);

        foreach (var entry in parseResult.Entries)
        {
            if (!typeGroups.ContainsKey(entry.Type))
            {
                typeGroups[entry.Type] = new List<XamlEntry>();
                typeOrder.Add(entry.Type);
            }

            typeGroups[entry.Type].Add(entry);
        }

        // Build a nested static class for each XAML type.
        var nestedClasses = new List<MemberDeclarationSyntax>(typeOrder.Count);
        for (int i = 0; i < typeOrder.Count; i++)
        {
            var nestedClass = BuildNestedClass(typeOrder[i], typeGroups[typeOrder[i]]);

            // Add a blank line before every subclass except the first.
            if (i > 0)
                nestedClass = nestedClass.WithLeadingTrivia(LineFeed, LineFeed);

            nestedClasses.Add(nestedClass);
        }

        // Build the outer static class (named after the XAML file, with Keys suffix).
        var outerClass = ClassDeclaration(SanitizeIdentifier(parseResult.FileName) + "Keys")
            .AddModifiers(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword))
            .AddMembers(nestedClasses.ToArray());

        // Wrap in a block-scoped namespace with the auto-generated header as leading trivia.
        var namespaceDecl = NamespaceDeclaration(ParseName(namespaceName))
            .AddMembers(outerClass)
            .WithLeadingTrivia(
                Comment("// <auto-generated/>"),
                LineFeed);

        var compilationUnit = CompilationUnit().AddMembers(namespaceDecl);

        return compilationUnit.NormalizeWhitespace().ToFullString();
    }

    private static ClassDeclarationSyntax BuildNestedClass(string typeName, List<XamlEntry> entries)
    {
        // Track used identifiers within this subclass to handle post-sanitization collisions.
        var usedIdentifiers = new HashSet<string>(StringComparer.Ordinal);
        var members = new List<MemberDeclarationSyntax>(entries.Count);

        foreach (var entry in entries)
        {
            var identifier = MakeUniqueIdentifier(SanitizeIdentifier(entry.Key), usedIdentifiers);
            usedIdentifiers.Add(identifier);
            members.Add(BuildConstString(identifier, entry.Key));
        }

        return ClassDeclaration(SanitizeIdentifier(typeName))
            .AddModifiers(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword))
            .AddMembers(members.ToArray());
    }

    private static FieldDeclarationSyntax BuildConstString(string identifier, string value)
    {
        // SyntaxFactory.Literal handles all necessary string escaping automatically.
        var initializer = EqualsValueClause(
            LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(value)));

        var variable = VariableDeclarator(identifier).WithInitializer(initializer);

        return FieldDeclaration(
                VariableDeclaration(PredefinedType(Token(SyntaxKind.StringKeyword)))
                    .AddVariables(variable))
            .AddModifiers(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.ConstKeyword));
    }

    /// <summary>
    /// Converts an arbitrary string into a valid C# identifier.
    /// </summary>
    internal static string SanitizeIdentifier(string name)
    {
        if (string.IsNullOrEmpty(name))
            return "_";

        var sb = new System.Text.StringBuilder(name.Length);

        for (int i = 0; i < name.Length; i++)
        {
            char c = name[i];

            if (i == 0 && char.IsDigit(c))
                sb.Append('_');

            if (char.IsLetterOrDigit(c) || c == '_')
                sb.Append(c);
            else
                sb.Append('_');
        }

        var result = sb.ToString();

        // Prefix with _ if the sanitized result is a C# keyword.
        if (CSharpKeywords.Contains(result))
            result = "_" + result;

        return result;
    }

    private static string MakeUniqueIdentifier(string candidate, HashSet<string> used)
    {
        if (!used.Contains(candidate))
            return candidate;

        int suffix = 1;
        string unique;
        do
        {
            unique = $"{candidate}_{suffix++}";
        } while (used.Contains(unique));

        return unique;
    }
}

