using System.Text;
using Xamlizer.Models;

namespace Xamlizer;

/// <summary>
/// Generates C# source code from a <see cref="XamlParseResult"/>.
/// </summary>
internal static class CSharpCodeGenerator
{ 
    // All C# reserved keywords that cannot be used as plain identifiers.
    private static readonly HashSet<string> CSharpKeywords = new HashSet<string>(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
        "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw",
        "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using",
        "virtual", "void", "volatile", "while",
    };

    /// <summary>
    /// Generates a C# source file from the parsed XAML result.
    /// </summary>
    public static string Generate(XamlParseResult parseResult, string namespaceName)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static class {SanitizeIdentifier(parseResult.FileName)}");
        sb.AppendLine("    {");

        // Group entries by type in first-appearance order, preserving document order within each type.
        var typeOrder = new List<string>();
        var typeGroups = new Dictionary<string, List<XamlEntry>>(StringComparer.Ordinal);

        foreach (var entry in parseResult.Entries)
        {
            if (!typeGroups.ContainsKey(entry.Type))
            {
                typeGroups[entry.Type] = [];
                typeOrder.Add(entry.Type);
            }

            typeGroups[entry.Type].Add(entry);
        }

        for (int i = 0; i < typeOrder.Count; i++)
        {
            var typeName = typeOrder[i];
            var entries = typeGroups[typeName];

            sb.AppendLine($"        public static class {SanitizeIdentifier(typeName)}");
            sb.AppendLine("        {");

            // Track used identifiers within this subclass to handle post-sanitization collisions.
            var usedIdentifiers = new HashSet<string>(StringComparer.Ordinal);

            foreach (var entry in entries)
            {
                var identifier = MakeUniqueIdentifier(SanitizeIdentifier(entry.Key), usedIdentifiers);
                usedIdentifiers.Add(identifier);

                sb.AppendLine($"            public const string {identifier} = \"{EscapeStringLiteral(entry.Key)}\";");
            }

            sb.AppendLine("        }");

            if (i < typeOrder.Count - 1)
                sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Converts an arbitrary string into a valid C# identifier.
    /// </summary>
    internal static string SanitizeIdentifier(string name)
    {
        if (string.IsNullOrEmpty(name))
            return "_";

        var sb = new StringBuilder(name.Length);

        for (int i = 0; i < name.Length; i++)
        {
            char c = name[i];

            if (i == 0 && char.IsDigit(c))
                sb.Append('_');

            if (char.IsLetterOrDigit(c) || c == '_')
                sb.Append(c);
            else
                sb.Append('_');
        }

        var result = sb.ToString();

        // Prefix with _ if the sanitized result is a C# keyword.
        if (CSharpKeywords.Contains(result))
            result = "_" + result;

        return result;
    }

    /// <summary>
    /// Escapes a string value for safe use inside a C# string literal.
    /// </summary>
    internal static string EscapeStringLiteral(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n")
            .Replace("\t", "\\t");
    }

    private static string MakeUniqueIdentifier(string candidate, HashSet<string> used)
    {
        if (!used.Contains(candidate))
            return candidate;

        int suffix = 1;
        string unique;
        do
        {
            unique = $"{candidate}_{suffix++}";
        } while (used.Contains(unique));

        return unique;
    }
}
