using Xamlizer.Models;
using Xunit;

namespace Xamlizer.Tests;

public class CSharpCodeGeneratorTests
{
    #region Tests

    [Theory]
    [InlineData("Primary", "Primary")]
    [InlineData("Gray100", "Gray100")]
    [InlineData("100Gray", "_100Gray")]
    [InlineData("My-Key", "My_Key")]
    [InlineData("My Key", "My_Key")]
    [InlineData("", "_")]
    [InlineData("class", "_class")]
    [InlineData("string", "_string")]
    [InlineData("namespace", "_namespace")]
    [InlineData("_valid", "_valid")]
    public void SanitizeIdentifier_VariousInputs_ReturnsExpected(string input, string expected)
    {
        Assert.Equal(expected, CSharpCodeGenerator.SanitizeIdentifier(input));
    }

    [Fact]
    public void Generate_SingleTypeAndKey_ContainsAutoGeneratedHeader()
    {
        var result = GenerateSingle("Colors", "Color", "Primary");
        Assert.Contains("// <auto-generated/>", result);
    }

    [Fact]
    public void Generate_SingleTypeAndKey_ContainsNamespace()
    {
        var result = GenerateSingle("Colors", "Color", "Primary", namespaceName: "MyApp");
        Assert.Contains("namespace MyApp", result);
    }

    [Fact]
    public void Generate_SingleTypeAndKey_ContainsOuterClass()
    {
        var result = GenerateSingle("Colors", "Color", "Primary");
        Assert.Contains("public static class ColorsKeys", result);
    }

    [Fact]
    public void Generate_SingleTypeAndKey_ContainsNestedTypeClass()
    {
        var result = GenerateSingle("Colors", "Color", "Primary");
        Assert.Contains("public static class Color", result);
    }

    [Fact]
    public void Generate_SingleTypeAndKey_ContainsConstStringMember()
    {
        var result = GenerateSingle("Colors", "Color", "Primary");
        Assert.Contains("public const string Primary = \"Primary\";", result);
    }

    [Fact]
    public void Generate_FileNameStartingWithDigit_SanitizesOuterClassName()
    {
        var result = GenerateSingle("1Colors", "Color", "Primary");
        Assert.Contains("public static class _1ColorsKeys", result);
    }

    [Fact]
    public void Generate_KeyNameIsKeyword_SanitizesMemberName()
    {
        var result = GenerateSingle("Colors", "Color", "class");
        Assert.Contains("public const string _class = \"class\";", result);
    }

    [Fact]
    public void Generate_TwoTypes_BothTypesPresent()
    {
        var entries = new List<XamlEntry>
        {
            new XamlEntry("Color", "Primary"),
            new XamlEntry("SolidColorBrush", "PrimaryBrush"),
        };
        var parseResult = new XamlParseResult("Colors", entries);
        var source = CSharpCodeGenerator.Generate(parseResult, "MyApp");

        Assert.Contains("public static class Color", source);
        Assert.Contains("public static class SolidColorBrush", source);
    }

    [Fact]
    public void Generate_TwoTypes_TypesInFirstAppearanceOrder()
    {
        var entries = new List<XamlEntry>
        {
            new XamlEntry("Color", "Primary"),
            new XamlEntry("SolidColorBrush", "PrimaryBrush"),
        };
        var parseResult = new XamlParseResult("Colors", entries);
        var source = CSharpCodeGenerator.Generate(parseResult, "MyApp");

        var colorIndex = source.IndexOf("public static class Color", StringComparison.Ordinal);
        var brushIndex = source.IndexOf("public static class SolidColorBrush", StringComparison.Ordinal);
        Assert.True(colorIndex < brushIndex, "Color should appear before SolidColorBrush");
    }

    [Fact]
    public void Generate_InterleavedTypes_GroupsKeysCorrectly()
    {
        // XAML with Color, SolidColorBrush, then more Colors — like the real Colors.xaml.
        var entries = new List<XamlEntry>
        {
            new XamlEntry("Color", "Primary"),
            new XamlEntry("SolidColorBrush", "PrimaryBrush"),
            new XamlEntry("Color", "Yellow100Accent"),
        };
        var parseResult = new XamlParseResult("Colors", entries);
        var source = CSharpCodeGenerator.Generate(parseResult, "MyApp");

        // Both Color keys should be in the Color subclass.
        var colorClassStart = source.IndexOf("public static class Color", StringComparison.Ordinal);
        var colorClassEnd = source.IndexOf("public static class SolidColorBrush", StringComparison.Ordinal);
        var colorSection = source[colorClassStart..colorClassEnd];

        Assert.Contains("Primary", colorSection);
        Assert.Contains("Yellow100Accent", colorSection);
    }
    
    [Fact]
    public void Generate_DuplicateSanitizedIdentifiers_AppendsSuffix()
    {
        // "My-Key" and "My_Key" both sanitize to "My_Key".
        var entries = new List<XamlEntry>
        {
            new XamlEntry("Color", "My-Key"),
            new XamlEntry("Color", "My_Key"),
        };
        var parseResult = new XamlParseResult("Colors", entries);
        var source = CSharpCodeGenerator.Generate(parseResult, "MyApp");

        Assert.Contains("public const string My_Key = \"My-Key\";", source);
        Assert.Contains("public const string My_Key_1 = \"My_Key\";", source);
    }

    [Fact]
    public void Generate_ColorsXaml_ProducesExpectedColorCount()
    {
        var parseResult = XamlParser.Parse("Colors", TestResources.GetColorsXaml());
        var source = CSharpCodeGenerator.Generate(parseResult, "MyApp");

        // 22 Color const declarations.
        var count = CountOccurrences(source, "public const string", withinClass: "public static class Color");
        Assert.Equal(22, count);
    }

    [Fact]
    public void Generate_ColorsXaml_ProducesExpectedSolidColorBrushCount()
    {
        var parseResult = XamlParser.Parse("Colors", TestResources.GetColorsXaml());
        var source = CSharpCodeGenerator.Generate(parseResult, "MyApp");

        var count = CountOccurrences(source, "public const string", withinClass: "public static class SolidColorBrush");
        Assert.Equal(13, count);
    }

    [Fact]
    public void Generate_ColorsXaml_ContainsPrimaryKey()
    {
        var parseResult = XamlParser.Parse("Colors", TestResources.GetColorsXaml());
        var source = CSharpCodeGenerator.Generate(parseResult, "MyApp");

        Assert.Contains("public const string Primary = \"Primary\";", source);
    }

    [Fact]
    public void Generate_ColorsXaml_ContainsPrimaryBrushKey()
    {
        var parseResult = XamlParser.Parse("Colors", TestResources.GetColorsXaml());
        var source = CSharpCodeGenerator.Generate(parseResult, "MyApp");

        Assert.Contains("public const string PrimaryBrush = \"PrimaryBrush\";", source);
    }

    #endregion

    #region Test Helpers

    private static string GenerateSingle(
        string fileName,
        string typeName,
        string key,
        string namespaceName = "MyApp")
    {
        var entries = new List<XamlEntry> { new XamlEntry(typeName, key) };
        var parseResult = new XamlParseResult(fileName, entries);
        return CSharpCodeGenerator.Generate(parseResult, namespaceName);
    }

    /// <summary>
    /// Counts occurrences of <paramref name="needle"/> in the section of
    /// <paramref name="source"/> that starts after <paramref name="withinClass"/>.
    /// Matches are constrained to word boundaries so "Color" does not match "Colors".
    /// </summary>
    private static int CountOccurrences(string source, string needle, string withinClass)
    {
        // Find the class declaration with a word-boundary check: the character immediately
        // after the search string must not be a letter/digit/underscore.
        int start = -1;
        int searchFrom = 0;
        while (true)
        {
            int idx = source.IndexOf(withinClass, searchFrom, StringComparison.Ordinal);
            if (idx < 0) break;
            int afterMatch = idx + withinClass.Length;
            bool atWordBoundary = afterMatch >= source.Length
                                  || (!char.IsLetterOrDigit(source[afterMatch]) && source[afterMatch] != '_');
            if (atWordBoundary) { start = idx; break; }
            searchFrom = idx + 1;
        }
        if (start < 0) return 0;

        // Find the opening brace of this class.
        var braceStart = source.IndexOf('{', start);
        if (braceStart < 0) return 0;

        // Walk forward to find the matching closing brace (depth tracking).
        int depth = 0;
        int end = braceStart;
        for (int i = braceStart; i < source.Length; i++)
        {
            if (source[i] == '{') depth++;
            else if (source[i] == '}')
            {
                depth--;
                if (depth == 0) { end = i; break; }
            }
        }

        var section = source[braceStart..end];
        int count = 0;
        int pos = 0;
        while ((pos = section.IndexOf(needle, pos, StringComparison.Ordinal)) >= 0)
        {
            count++;
            pos += needle.Length;
        }
        return count;
    }

    #endregion
}
